package entities;

/*

 * Depicts all the possible categories for written works
 */
public enum Genre {
    SCIENCE_FICTION, SATIRE, DRAMA, ACTION, ROMANCE, MYSTERY,
    HORROR, SELF_HELP, GUIDE, TRAVEL, CHILDREN, RELIGIOUS,
    SCIENCE, HISTORY, MATH, POETRY, ENCYCLOPEDIA, DICTIONARY,
    COMICS, ART, COOKBOOK, JOURNAL, BIOGRAPHY, AUTOBIOGRAPHY,
    FANTASY
}
